# Google Cloud Config file
application: brutto-netto-rechner
version: 1

runtime: python27
api_version: 1

threadsafe: true

handlers:

- url: /.*
  script: FlaskWebProject.views.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: pycrypto
  version: "latest"
