branch-defaults:
  default:
    environment: amos-proj1
global:
  application_name: rechner-flask
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.03 v1.3.1 running Python 2.7
  default_region: null
  profile: null
  sc: null
